### PR TITLE
Itoffshore master

### PR DESCRIPTION
**Pull request by escopecz**
Hey! I fixed the BC compatibility issue, using the plugin in the Joomla installed to a subfolder and made some Joomla code standards modifications.

Merge this and I'll merge your PR to the master.

Thanks!

### CODE REVIEW

**Comment by itoffshore** [comment]
I think the [Loading Fonts](https://github.com/escopecz/plg_githubrepo/commit/0b1c8e36a35a8d580de49400efcf6edd3c2d25ab) commit is wrong - @font-face needs an absolute path with a leading forward slash.

You can see at the [bottom of my page](http://it-offshore.co.uk/linux/alpine-linux/25-alpine-linux-luks-encrypted-installations) icons showing next to the filenames - on [your page](http://www.escope.cz/en/extensions/github-repo/github-repo-documentation) the fonts show a "t" instead of an icon. 

Can you revert your [last commit](https://github.com/escopecz/plg_githubrepo/commit/0b1c8e36a35a8d580de49400efcf6edd3c2d25ab) ?

**Comment by itoffshore** [comment]
See [here](http://www.codingforums.com/html-and-css/252394-@font-face-not-working.html) for the absolute paths.

let me try & `cherry-pick` the other 2 commits

**Comment by escopecz** [comment]
Sorry, man, but that's not true. You should test it before you act. Take a look at this screenshot:
font-url-with-slash
I cannot merge your PR this way.

**Comment by itoffshore** [comment]
I have tested it on [my live site](http://it-offshore.co.uk/linux/alpine-linux/25-alpine-linux-luks-encrypted-installations) as noted above in both Firefox & IE.

**Comment by escopecz** [comment]
Well, that's great, but the fonts will not load if your site would have been in a sub-folder. For example if you have your Joomla website installed on address http://it-offshore.co.uk/joomla.

If you don't want to create the new Joomla installation in a sub-folder and test it there I propose you test the plugin with all my changes. If it will still work for you, you'll merge the commit you don't like for some reason and I'll merge your PR with the main repository and release new version.

**Comment by itoffshore** [comment]
ok so we are both right - your version works for subdirectory installs & mine for root installs.

Let me see if there is a way in `js` or `php` to detect the installed path so the `@font-face` path can be set correctly.

**Comment by escopecz** [comment]
Tell me just one thing. Have you tried my version on your website? I don't think so.

Could you send me similar screenshot I published here? With visible URL and JS console?

**Comment by itoffshore** [comment]
I found the bug & yes I have tried using a `@font-face` path without a leading forward slash while I was trying to get it to work on my website - it does NOT work for a joomla root install

**Comment by itoffshore** [comment]
broken fonts + firebug - your commit does not work for root installs
broken-fonts

**Pull request closed without merging**
